### ISSUE TITLE
References across markdown files

### ISSUE THREAD

**Issue by aholmes** [AI-READI/software-development-best-practices#3]
The current markdown files contain several references that are great for readers to form a better idea of how the documents fit together, but they can be made simpler to navigate. For example, in [Project setup](https://github.com/AI-READI/software-development-best-practices/blob/main/main/software-development-best-practices-for-ai-readi/project-setup.md#1-project-setup) each item contains a `[Ref: #]` section at the end. It would be useful for these to link directly to the specific references listed on [Overview and resources](https://github.com/AI-READI/software-development-best-practices/blob/main/main/software-development-best-practices-for-ai-readi/overview-and-resources.md#overview-and-resources). This can be done through the use of headers in the "Overview" document, and linking to those, or with the use of named anchors, e.g., `<a name="foo"></a>` and linking to those.

**Comment by bvhpatel** [comment]
Thanks for the suggestion! We have implemented that here: https://github.com/AI-READI/software-development-best-practices/blob/tools-core-comments/main/software-development-best-practices-for-ai-readi. This will be pushed to the main branch when we have addressed all the comments from the Tools Core.
